CREATE DATABASE УП01_ИСПП5_Иванченко_ИВ
ON PRIMARY (
NAME= btidata,
FILENAME='\\DESKTOP-7J49MA8\c$\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\btidata.mdf',
SIZE=100MB,
MAXSIZE=200, FILEGROWTH=20
)
LOG ON (
NAME= btilog,
FILENAME='\\DESKTOP-7J49MA8\c$\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\btilog.ldf',
SIZE=100MB,
MAXSIZE=200,
FILEGROWTH=20
)
